apiVersion: v1
kind: ConfigMap
metadata:
  name: service-database-vars-lorem
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  serviceName: lorem
  aliasName: lorem-db-rw
  databaseResourceName: lorem-database
  databaseName: lorem
  databaseOwner: lorem_app
  schemaName: lorem
  schemaOwner: lorem_app
  roleApp: lorem_app
  roleAppRo: lorem_app_ro
  roleAppRw: lorem_app_rw
  roleAppMig: lorem_app_mig
  roleAppRoA: lorem_app_ro_a
  roleAppRoB: lorem_app_ro_b
  roleAppRwA: lorem_app_rw_a
  roleAppRwB: lorem_app_rw_b
  roleAppMigA: lorem_app_mig_a
  secretRoA: lorem-db-app-ro-a
  secretRoB: lorem-db-app-ro-b
  secretRwA: lorem-db-app-rw-a
  secretRwB: lorem-db-app-rw-b
  secretMigA: lorem-db-app-mig-a
  provisionJobName: lorem-db-provision
  provisionSqlKey: provision-lorem.sql
  provisionSql: |
    REVOKE ALL ON DATABASE lorem FROM PUBLIC;
    GRANT CONNECT ON DATABASE lorem TO lorem_app, lorem_app_ro, lorem_app_rw, lorem_app_mig;
    DROP SCHEMA IF EXISTS public;

    GRANT USAGE ON SCHEMA lorem TO lorem_app_ro;
    GRANT USAGE ON SCHEMA lorem TO lorem_app_rw;

    ALTER DEFAULT PRIVILEGES FOR ROLE lorem_app IN SCHEMA lorem
      GRANT SELECT ON TABLES TO lorem_app_ro;
    ALTER DEFAULT PRIVILEGES FOR ROLE lorem_app IN SCHEMA lorem
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO lorem_app_rw;
    ALTER DEFAULT PRIVILEGES FOR ROLE lorem_app IN SCHEMA lorem
      GRANT USAGE, SELECT ON SEQUENCES TO lorem_app_rw;
