apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cluster-vars-lorem
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  clusterName: lorem-postgres
  postinitName: service-database-postinit-sql-lorem
