apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../../components/cluster/shared
  - ../../base
  - verification.yaml
components:
  - ../../components/service-wiring/lorem
  - ../../components/service-wiring/ipsum
  - ../../components/service-wiring/dolor
  - ../../components/cluster-binding
patches:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
    patch: |-
      - op: replace
        path: /spec/primaryUpdateStrategy
        value: unsupervised
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Database
    patch: |-
      - op: replace
        path: /spec/databaseReclaimPolicy
        value: delete
