apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../../components/cluster/shared
  - ../../base
  - verification.yaml
components:
  - ../../components/service-wiring/lorem
  - ../../components/service-wiring/ipsum
  - ../../components/service-wiring/dolor
  - ../../components/cluster-binding
  - ../_ephemeral-relaxation
