apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cluster-binding-lorem
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  clusterName: service-databases-shared-postgres
  clusterRwFqdn: service-databases-shared-postgres-rw.datastores-stg.svc.cluster.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cluster-binding-ipsum
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  clusterName: service-databases-shared-postgres
  clusterRwFqdn: service-databases-shared-postgres-rw.datastores-stg.svc.cluster.local
