apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - external-secrets.yaml
  - database.yaml
  - provisioning-job.yaml
patches:
  - path: managed-roles-patch.yaml
    target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: cnpg-eso-multidb-verification
