apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: web-app
  name: web-app
  namespace: stg
spec:
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  strategy:
    blueGreen:
      activeService: web-app-active
      autoPromotionEnabled: true
      previewService: web-app-preview
      scaleDownDelaySeconds: 35
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - image: ghcr.io/alex-on-java/web-app@sha256:732e9153802e64029f13f49028663334afad0a2ceaccb6da1366a6bc92994072
        imagePullPolicy: IfNotPresent
        name: web-app
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 32Mi
