apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cluster-values-shared
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  clusterName: service-databases-shared-postgres
  postinitName: service-database-postinit-sql
