apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cluster-vars-ipsum
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  clusterName: ipsum-postgres
  postinitName: service-database-postinit-sql-ipsum
