apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      kind: ConfigMap
      name: postgres-cluster-binding-lorem
      fieldPath: data.clusterName
    targets:
      - select:
          kind: Database
          name: lorem-database
        fieldPaths:
          - spec.cluster.name
  - source:
      kind: ConfigMap
      name: postgres-cluster-binding-lorem
      fieldPath: data.clusterRwFqdn
    targets:
      - select:
          kind: Service
          name: lorem-db-rw
        fieldPaths:
          - spec.externalName
  - source:
      kind: ConfigMap
      name: postgres-cluster-binding-ipsum
      fieldPath: data.clusterName
    targets:
      - select:
          kind: Database
          name: ipsum-database
        fieldPaths:
          - spec.cluster.name
  - source:
      kind: ConfigMap
      name: postgres-cluster-binding-ipsum
      fieldPath: data.clusterRwFqdn
    targets:
      - select:
          kind: Service
          name: ipsum-db-rw
        fieldPaths:
          - spec.externalName
