apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-cluster-values-lorem
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  clusterName: cnpg-eso-lorem
  postinitName: cnpg-verification-postinit-sql-lorem
