apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: promote-platform-app
spec:
  vars:
    - name: appName
    - name: argoAppName
    - name: imageRepo
    - name: warehouseImageURL
    - name: gitRepoURL
      value: https://github.com/alex-on-java/portfolio-project.git
  steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.gitRepoURL }}
        checkout:
          - commit: ${{ commitFrom(vars.gitRepoURL).ID }}
            path: ./src
          - branch: stage/${{ sharedConfigMap('cluster-identity').branchPrefix }}/${{ ctx.stage }}
            create: true
            path: ./out

    - uses: git-clear
      config:
        path: ./out

    - uses: kustomize-set-image
      as: update-image
      config:
        path: ./src/gitops/apps/platform/${{ vars.appName }}/overlays/${{ sharedConfigMap('cluster-identity').overlayTarget }}/${{ sharedConfigMap('cluster-identity').clusterLifecycle }}
        images:
          - image: ${{ vars.warehouseImageURL }}
            name: ${{ vars.imageRepo }}
            newName: ${{ vars.imageRepo }}
            digest: ${{ imageFrom(vars.warehouseImageURL).Digest }}

    - uses: kustomize-build
      as: build
      config:
        path: ./src/gitops/apps/platform/${{ vars.appName }}/overlays/${{ sharedConfigMap('cluster-identity').overlayTarget }}/${{ sharedConfigMap('cluster-identity').clusterLifecycle }}
        outPath: ./out

    - uses: git-commit
      as: commit
      config:
        path: ./out
        message: "Promote ${{ sharedConfigMap('cluster-identity').branchPrefix }}/${{ ctx.stage }}: ${{ vars.appName }} ${{ imageFrom(vars.warehouseImageURL).Tag }}"

    - uses: git-push
      config:
        path: ./out

    - uses: argocd-update
      as: sync
      config:
        apps:
          - name: ${{ vars.argoAppName }}
