apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: kargo.akuity.io
      version: v1alpha1
      kind: Stage
      name: dev
    patch: |
      - op: add
        path: /spec/verification
        value:
          analysisTemplates:
            - name: http-health-check-job
              kind: ClusterAnalysisTemplate
          args:
            - name: service-url
              value: "${{ 'http://' + vars.appName + '-active.' + vars.env + '.svc.cluster.local' + vars.healthPath }}"
  - target:
      group: kargo.akuity.io
      version: v1alpha1
      kind: Stage
      name: stg
    patch: |
      - op: add
        path: /spec/verification
        value:
          analysisTemplates:
            - name: http-health-check-job
              kind: ClusterAnalysisTemplate
          args:
            - name: service-url
              value: "${{ 'http://' + vars.appName + '-active.' + vars.env + '.svc.cluster.local' + vars.healthPath }}"
