apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - gatewayclass.yaml

patches:
  - target:
      kind: Gateway
      name: portfolio-edge-gateway
    patch: |-
      - op: replace
        path: /spec/gatewayClassName
        value: contour
