apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postinit-sql.yaml
  - cluster.yaml
patches:
  - path: operator-roundtrip-defaults.yaml
    target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
