apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-cluster-values-shared
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  clusterName: cnpg-eso-multidb-verification
  postinitName: cnpg-verification-postinit-sql
