apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-cluster-values-dolor
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  clusterName: cnpg-eso-dolor
  postinitName: cnpg-verification-postinit-sql-dolor
