apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prd
resources:
  - ../../../base
  - http-route-active.yaml
  - http-route-preview.yaml
images:
  - name: ghcr.io/alex-on-java/web-app
    newName: ghcr.io/alex-on-java/web-app
    newTag: "sha256:placeholder"
