apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: cnpg-eso-verification-password
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  length: 32
  digits: 8
  symbols: 4
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-verification-lorem-app-ro-a
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: cnpg-verification-lorem-app-ro-a
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: lorem_app_ro_a
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: cnpg-eso-verification-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-verification-lorem-app-ro-b
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: cnpg-verification-lorem-app-ro-b
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: lorem_app_ro_b
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: cnpg-eso-verification-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-verification-lorem-app-rw-a
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: cnpg-verification-lorem-app-rw-a
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: lorem_app_rw_a
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: cnpg-eso-verification-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-verification-lorem-app-rw-b
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: cnpg-verification-lorem-app-rw-b
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: lorem_app_rw_b
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: cnpg-eso-verification-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-verification-lorem-app-mig-a
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: cnpg-verification-lorem-app-mig-a
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: lorem_app_mig_a
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: cnpg-eso-verification-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-verification-ipsum-app-ro-a
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: cnpg-verification-ipsum-app-ro-a
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: ipsum_app_ro_a
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: cnpg-eso-verification-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-verification-ipsum-app-ro-b
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: cnpg-verification-ipsum-app-ro-b
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: ipsum_app_ro_b
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: cnpg-eso-verification-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-verification-ipsum-app-rw-a
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: cnpg-verification-ipsum-app-rw-a
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: ipsum_app_rw_a
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: cnpg-eso-verification-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-verification-ipsum-app-rw-b
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: cnpg-verification-ipsum-app-rw-b
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: ipsum_app_rw_b
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: cnpg-eso-verification-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-verification-ipsum-app-mig-a
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: cnpg-verification-ipsum-app-mig-a
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: ipsum_app_mig_a
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: cnpg-eso-verification-password
