apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - generated-secrets.yaml
  - postinit-sql.yaml
  - provisioning-sql.yaml
  - cluster.yaml
  - database-lorem.yaml
  - database-ipsum.yaml
  - provisioning-jobs.yaml
  - verification.yaml
