apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: cnpg-eso-verification-password
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  length: 32
  digits: 8
  symbols: 4
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
