global:
  leaderElection:
    namespace: cert-manager

crds:
  enabled: true
  keep: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 64Mi

webhook:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 64Mi

cainjector:
  resources:
    requests:
      cpu: 50m
      memory: 192Mi
      ephemeral-storage: 64Mi
    limits:
      cpu: 100m
      memory: 384Mi
      ephemeral-storage: 64Mi

startupapicheck:
  resources:
    requests:
      cpu: 50m
      memory: 52Mi
      ephemeral-storage: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 64Mi

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: cert-manager-dns@cv-driven-dev-e-commerce.iam.gserviceaccount.com
