#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "jinja2",
#     "pyyaml",
#     "click",
# ]
# ///
import difflib
import sys
from pathlib import Path

import click
import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

HERE = Path(__file__).resolve().parent
TEMPLATES_DIR = HERE / "templates"
GENERATED_DIR = HERE / "generated"
SERVICES_FILE = HERE / "services.yaml"

BANNER = "# Generated by generate.py from templates/ and services.yaml. Do not edit by hand.\n"


def load_services() -> list[str]:
    data = yaml.safe_load(SERVICES_FILE.read_text())
    services = data["services"]
    if not services:
        raise click.ClickException("services.yaml lists no services")
    if len(services) != len(set(services)):
        raise click.ClickException("services.yaml has duplicate service names")
    for name in services:
        if not name.isidentifier() or not name.islower():
            raise click.ClickException(
                f"service name {name!r} must be a lowercase identifier "
                "(it becomes a PostgreSQL role prefix and a Kubernetes name segment)"
            )
    return services


def render(services: list[str]) -> dict[str, str]:
    env = Environment(
        loader=FileSystemLoader(TEMPLATES_DIR),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
    )
    outputs: dict[str, str] = {}
    for template_path in sorted(TEMPLATES_DIR.glob("*.j2")):
        out_name = template_path.name.removesuffix(".j2")
        template = env.get_template(template_path.name)
        body = template.render(services=services)
        lines = [line.rstrip() for line in (BANNER + body).splitlines()]
        outputs[out_name] = "\n".join(lines).rstrip("\n") + "\n"
    return outputs


@click.command()
@click.option(
    "--check",
    is_flag=True,
    help="Render in memory and fail if generated/ differs, without writing.",
)
def main(check: bool) -> None:
    services = load_services()
    outputs = render(services)

    if check:
        drift = []
        existing = {p.name for p in GENERATED_DIR.glob("*.yaml")}
        if existing != set(outputs):
            drift.append(
                f"file set differs: on disk {sorted(existing)}, expected {sorted(outputs)}"
            )
        for name, expected in outputs.items():
            actual = (GENERATED_DIR / name).read_text() if (GENERATED_DIR / name).exists() else ""
            if actual != expected:
                diff = "".join(
                    difflib.unified_diff(
                        actual.splitlines(keepends=True),
                        expected.splitlines(keepends=True),
                        fromfile=f"generated/{name}",
                        tofile=f"expected/{name}",
                    )
                )
                drift.append(diff)
        if drift:
            click.echo("\n".join(drift), err=True)
            raise click.ClickException(
                "generated/ is stale — run generate.py and commit the result"
            )
        click.echo(f"generated/ is up to date for services: {', '.join(services)}")
        return

    GENERATED_DIR.mkdir(exist_ok=True)
    for stale in GENERATED_DIR.glob("*.yaml"):
        if stale.name not in outputs:
            stale.unlink()
    for name, body in outputs.items():
        (GENERATED_DIR / name).write_text(body)
    click.echo(f"Wrote {len(outputs)} files for services: {', '.join(services)}")


if __name__ == "__main__":
    sys.exit(main())
