apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: web-app-demo-generated
spec:
  length: 32
  digits: 8
  symbols: 0
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-app-demo-generated
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: web-app-demo-generated
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: web-app-demo-generated
      rewrite:
        - regexp:
            source: "password"
            target: "demo-generated"
